In [7]:
import numpy as np
import pandas as pd
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [2]:
NAME = "multi"
PATH = "../data/evaluation/{}-results.pkl".format(NAME)

df = pd.read_pickle(PATH)

In [3]:
# df['true_roll'] *= -1
# df['true_yaw'] *= -1
df['true_pitch'] *= -1

In [4]:
df

,image_id,image_frame,roll,yaw,pitch,true_roll,true_pitch,true_yaw,error
0,1,3,-3.173777,4.474857,-14.288164,-1.566632,-7.607223,3.290995,21.927369
1,1,4,-2.819786,3.405285,-15.729584,-1.930131,-7.650885,3.889411,23.385480
2,1,5,-2.887421,5.001151,-14.952924,-1.946089,-7.445381,3.664674,22.438142
3,1,6,-2.817974,4.602928,-14.972390,-1.896884,-7.455991,3.795916,22.442896
4,1,7,-2.961393,3.243202,-14.107788,-2.123386,-7.729789,3.433040,21.838402
...,...,...,...,...,...,...,...,...,...
15673,24,618,-2.151425,-22.097605,-29.923514,-2.091429,-27.829273,1.649785,62.444558
15674,24,619,-3.212865,-20.274136,-28.125253,-1.574616,-27.642538,2.348748,60.181736
15675,24,620,-0.687591,-14.549567,-25.087853,-1.413197,-26.657115,1.891241,54.294032
15676,24,621,-0.778475,-10.265451,-26.222851,-1.915508,-25.749074,2.681087,53.560189
15677,24,622,-1.755592,-15.478843,-25.820093,-1.810187,-23.973104,3.647069,53.340069

In [5]:
df["mae_roll"] = np.abs(df["true_roll"] - df["roll"])
df["mae_pitch"] = np.abs(df["true_pitch"] - df["pitch"])
df["mae_yaw"] = np.abs(df["true_yaw"] - df["yaw"])

In [6]:
df[["mae_roll", "mae_pitch", "mae_yaw"]].mean()

mae_roll     6.801500
mae_pitch    6.613794
mae_yaw      8.696134
dtype: float64

In [ ]:

angles = res[["yaw", "pitch", "roll"]] # .drop_duplicates()
sns.jointplot(x="yaw", y="pitch", **kwargs)
sns.jointplot(x="yaw", y="roll", **kwargs)